export default {
  boards: [],
  board: null,
  members: [],
  member: null,
  users: [],
  user: null,
  auths: [],
  books: [],
  book: null,
  rooms: [],
  room:null,
  memberAuths:[],
  memberAuth:null,
  dates:[],
  memberRequest: null,
  // isManagerLogin: false,
  // isManagerLoginError: false,
  isLogin: false,
  isLoginError: false,
  lists: [],
  session: [],
}