export default {
  boards: [],
  board: null,
  members: [],
  member: null,
  users: [],
  user: null,
  auths: [],
  books: [],
  dates:[],
  book: null,
  memberRequest: null,
  isManagerLogin: false,
  isManagerLoginError: false,
  isLogin: false,
  isLoginError: false,
  lists: [],
  session: [],
}